### PR TITLE
Clarify how to run Tailwind command in CI

### PR DESCRIPTION
**Pull request by ghiculescu**
The current docs are a bit confusing, because only `rake` tasks get enhanced by this library, but there's also `rails` tasks that look the same.

I tried to make it a bit more clear.

Disclaimer: it's possible I've gotten confused and there's a much simpler recommended approach... I'd love for that to be true!

### CODE REVIEW

**Comment by flavorjones** [comment]
To simplify the message, should we just recommend one way to do it, and that's `bin/rails test:prepare test`?

**Comment by ghiculescu** [comment]
Yes, that's much better.

**Comment by ghiculescu** [comment]
Just one suggestion. I hope that https://github.com/rails/rails/pull/46664 will make all this irrelevant! Thanks for your help @flavorjones

**Comment by flavorjones** [comment]
Thanks for diving into the Rails tasks, I had just started down that path. homer-disappearing-into-a-bush.gif

**Comment by ghiculescu** [comment]
> Thanks for diving into the Rails tasks, I had just started down that path. homer-disappearing-into-a-bush.gif

Well I haven't quite got it working right, see my comment on the PR. Help is welcome!! 🙏

**Pull request merged**
