### PR TITLE
Add test for group-hover classes

### PR DESCRIPTION
**Pull request by andersklenke**
This adds a failing test for group hover classes as discussed in here https://github.com/rails/tailwindcss-rails/issues/20

cc. @kaspth

### CODE REVIEW

**Comment by kaspth** [comment]
So it feels like the focus/hover purging is normalizing the passed in CSS class such that `.group-hover` looks like it's being used even though it isn't https://github.com/rails/tailwindcss-rails/blob/1ff4d8fd817f81228cfdb8a39643ee92e6ef1bd4/lib/tailwindcss/purger.rb#L57

**Comment by andersklenke** [comment]
I believe this happens due to the `.group` class in the parent class. The word `group` will match with every single class that contains "group" afterwards. 
https://github.com/rails/tailwindcss-rails/blob/63c6058840032387878f1bd04e1f0c957364e446/test/fixtures/group_hover.html.erb#L1

**Comment by kaspth** [comment]
Ah! So we may need to throw a \b or \s in the final regex, to check for a word boundary or whitespace, respectively. Wanna try fiddling with either of those?

**Comment by andersklenke** [comment]
Sure! I will give it a try

**Comment by andersklenke** [comment]
A lot happened for me lately, so I haven't had the time to look at this yet. If anyone want to pick it up, feel free 🙂

**Pull request closed without merging**
