### PR TITLE
DRY default_files_with_class_names list of folders

### PR DESCRIPTION
**Pull request by andresgutgon**
# What?
Address this comment https://github.com/rails/tailwindcss-rails/pull/80#issuecomment-940782376

### CODE REVIEW

**Comment by dhh** [comment]
Actually, let's turn this into a setting, so you can tweak it.

**Comment by dhh** [comment]
This is what #74 was trying to do.

**Comment by dhh** [comment]
Think the other PR stalled. So feel free to finish it here first.

**Comment by dixpac** [comment]
Same as https://github.com/rails/tailwindcss-rails/pull/74#issuecomment-996700552

**Pull request closed without merging**
