### PR TITLE
Change CLASS_NAME_PATTERN to work also for haml templates

### PR DESCRIPTION
**Pull request by wnm**
This PR changes the CLASS_NAME_PATTERN to work for haml templates.

Since haml syntax uses dots to chain class names, I first removed the dot from the search pattern...

But, to make sure it still works for decimal spacing classes (e.g. `my-1.5`), I added a pattern to allow dots which are preceded by a number between 0-3 and followed by a 5.

By looking through the tailwind documentation, I think all the different class patterns are covered by a test already, so I'm not sure how to improve the test coverage... I'm happy to add more tests, but would need some input first, on what to test for...

### CODE REVIEW

**Comment by jumph4x** [comment]
Let's link this to #31, I almost got started on this not realizing you made moves already. 

Also, thanks for tackling it. <3

**Comment by wnm** [comment]
ugh, sorry about that I totally forgot to mention this PR in a comment in #31. I don't think I have the permission to link the issue as well...

**Comment by jontebol** [comment]
@wnm, do you think this will also work for [slim templates](http://slim-lang.com/)?

**Comment by wnm** [comment]
yes, it should work, at least for the default configuration which is using the same syntax for class names as haml, e.g: `.class-name`

**Comment by dhh** [comment]
Happy to see this adapted to the new purger.

**Comment by wnm** [comment]
@dhh done! I also added tests for slim syntax. it has a similar syntax (the same regex works), but [better tailwind support](https://github.com/slim-template/slim/pull/841/files)

**Review by krskibin — COMMENTED** [review]
:+1:

**Pull request merged**
