### PR TITLE
introduce specialized view for rails 8 authentication generator

### LINKED ISSUE #382: Generate styles for the sessions#new view template
The new [sessions generator](https://github.com/rails/rails/pull/52328/files#diff-ae43bad48cd5d0b053dc4f3e83960c38e0973e037b0a927b9f5cf1b46c33f041) has an html template that needs to be styled

### PR DESCRIPTION
**Pull request by flavorjones**
Dependent on https://github.com/rails/rails/pull/52442

Closes #382

Co-authored by @yshmarov

### CODE REVIEW

**Comment by flavorjones** [comment]
@yshmarov Can you give this a try before I merge it?

**Comment by dhh** [comment]
We should expand this to also cover the new password reset flow that landed on rails/main.

**Comment by dhh** [comment]
Good to go!

**Comment by yshmarov** [comment]
> @yshmarov Can you give this a try before I merge it?

Looks good

Screenshot 2024-08-04 at 16 40 19

Screenshot 2024-08-04 at 16 40 40

**Comment by flavorjones** [comment]
Thanks all! Merged. Will cut a release shortly.

**Pull request merged**
