### PR TITLE
generator: sync erb template

### LINKED ISSUE #341: Tailwind scaffold template is out of sync with rails/rails ERB scaffold template
https://github.com/rails/tailwindcss-rails/blob/main/lib/generators/tailwindcss/scaffold/templates/index.html.erb.tt is out of sync with https://github.com/rails/rails/blob/main/railties/lib/rails/generators/erb/scaffold/templates/index.html.erb.tt, namely it's missing the `<% content_for :title, "New event" %>`

Should template files be kept in sync (except the tailwind classes)?

Screenshot 2024-03-24 at 21 55 11

### PR DESCRIPTION
**Pull request by kinsomicrote**
This updates the ERB template to be in sync with the template in rails/rails

Fixes #341.

### CODE REVIEW

**Comment by kinsomicrote** [comment]
Hello @flavorjones 👋 

Any pointers on why the test is failing? I ran the test suite locally, and they all passed.

**Comment by javierjulio** [comment]
@kinsomicrote based on the errors occurring for the Rails 6.1 build, it looks like `model_resource_name` and `index_helper` have a different method signature at that version. So using `model_resource_name` as an example, [the v7.1 docs](https://api.rubyonrails.org/classes/Rails/Generators/NamedBase.html#method-i-model_resource_name) differ from [the v6.1 docs](https://api.rubyonrails.org/v6.1.0/classes/Rails/Generators/NamedBase.html#method-i-model_resource_name).

**Review by flavorjones — CHANGES_REQUESTED** [review]
@kinsomicrote Thank you for submitting this! I'd prefer to use a calling convention that's compatible with Rails 6.1 (rather than introduce version checks).

**Comment by kinsomicrote** [comment]
@flavorjones tests are passing now. Let me know if it's good to go.

**Comment by flavorjones** [comment]
Quick note for posterity: the `model_resource_name` change is from rails/rails#43611 which first appeared in Rails 7.0 and fixed namespaced models.

Namespaced models (e.g. `Admin::Monster`) still don't work with this PR but that's probably OK as long as we have to support Rails 6.1

**Comment by flavorjones** [comment]
I've rebased and squashed

**Comment by flavorjones** [comment]
@kinsomicrote Thanks so much for doing this work!!!

I'm going to open a second PR with your changes using the Rails 7.0 API so we can have a separate conversation about dropping Rails 6.1 feature support.

**Pull request merged**
