### PR TITLE
Add a tailwindcss:minify task

### PR DESCRIPTION
**Pull request by cyrildotcc**
Thanks to official Tailwind CSS documentation, with "Tailwind CLI, you can minify your CSS by adding the --minify flag" (source: https://tailwindcss.com/docs/optimizing-for-production).

Can we have first a minify task like this proposition on the tailwindcss-rails gem?

#greenit

### CODE REVIEW

**Comment by dixpac** [comment]
Thanks @cyrildotcc !
How would you setup production build to minify the output with `minify` task that you have added in this PR?

**Comment by dhh** [comment]
We should just minify all the time. Browsers unfold that anyway for debugging.

**Comment by dixpac** [comment]
> We should just minify all the time. Browsers unfold that anyway for debugging.

@cyrildotcc are you interested in working on this 🙏

**Comment by dhh** [comment]
Fixed via https://github.com/rails/tailwindcss-rails/commit/c76f5d22f9344d1ffe205352f189b75d3871d78e

**Comment by cyrildotcc** [comment]
@dixpac yes, another time maybe: @dhh did the job 🎉

**Pull request closed without merging**
