### PR TITLE
Move minify flag only for build task

### PR DESCRIPTION
**Pull request by achmiral**

### CODE REVIEW

**Comment by dhh** [comment]
What's the purpose of not just keeping it consistent?

**Comment by achmiral** [comment]
It's a little bit hard to debug when the `--minify` flag is on. For example when the styling is not applied on some element. So I have to check whether the class or styling has been generated or not in chrome developer tools or in "tailwind.css", especially for custom classes defined using the `@layer component` directive.

**Comment by ur5us** [comment]
To add another data point: I’m combining Bootstrap v3 with Tailwind in app. Admittedly, just is just a transition period. Anyway, Bootstrap v3 and many other CSS frameworks make their own assumptions by using a particular CSS reset for instance which usually includes CSS declarations for `html { … }` and `body { … }`. In those case, debugging with a minified Tailwind build is tricky.

**Comment by flavorjones** [comment]
I've create #198  which implements this feature more flexibly.

**Comment by flavorjones** [comment]
v2.0.13 has this feature, please see [the README](https://github.com/rails/tailwindcss-rails#update-assets-automatically) for an explanation.

**Pull request closed without merging**
